name: Calculate Factorial
on:
  workflow_dispatch:
    inputs:
      number:
        description: "Enter a number to calculate factorial"
        required: true
        type: number

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run factorial script
        id: factorial
        run: |
          chmod +x factorial.sh
          output=$(./factorial.sh ${{ github.event.inputs.number }})
          echo "RESULT=$output" >> $GITHUB_OUTPUT
          echo "$output"  # This will show in the pipeline logs